/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddRecordModal: typeof import('./src/components/profit/AddRecordModal.vue')['default']
    Calendar: typeof import('./src/components/profit/Calendar.vue')['default']
    Header: typeof import('./src/components/profit/Header.vue')['default']
    LoadingSpinner: typeof import('./src/components/common/LoadingSpinner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsModal: typeof import('./src/components/profit/SettingsModal.vue')['default']
    StatsCards: typeof import('./src/components/profit/StatsCards.vue')['default']
    Toast: typeof import('./src/components/common/Toast.vue')['default']
    UserSelector: typeof import('./src/components/profit/UserSelector.vue')['default']
  }
}
