/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddRecordModal: typeof import('./src/components/binance/AddRecordModal.vue')['default']
    BaseModal: typeof import('./src/components/common/BaseModal.vue')['default']
    Calendar: typeof import('./src/components/binance/Calendar.vue')['default']
    ConnectionStatus: typeof import('./src/components/bot/ConnectionStatus.vue')['default']
    FloatingButtons: typeof import('./src/components/bot/FloatingButtons.vue')['default']
    FloatingTaskButton: typeof import('./src/components/common/FloatingTaskButton.vue')['default']
    GradientText: typeof import('./src/components/common/GradientText.vue')['default']
    Header: typeof import('./src/components/binance/Header.vue')['default']
    LoadingSpinner: typeof import('./src/components/common/LoadingSpinner.vue')['default']
    LogModal: typeof import('./src/components/binance/LogModal.vue')['default']
    OKXAccountEditModal: typeof import('./src/components/okx/OKXAccountEditModal.vue')['default']
    OKXAddRecordModal: typeof import('./src/components/okx/OKXAddRecordModal.vue')['default']
    OKXCalendar: typeof import('./src/components/okx/OKXCalendar.vue')['default']
    OKXHeader: typeof import('./src/components/okx/OKXHeader.vue')['default']
    OKXLogModal: typeof import('./src/components/okx/OKXLogModal.vue')['default']
    OKXSettingsModal: typeof import('./src/components/okx/OKXSettingsModal.vue')['default']
    OKXStatsCards: typeof import('./src/components/okx/OKXStatsCards.vue')['default']
    OrderHistory: typeof import('./src/components/bot/OrderHistory.vue')['default']
    PriceInfo: typeof import('./src/components/bot/PriceInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsModal: typeof import('./src/components/binance/SettingsModal.vue')['default']
    StatsCards: typeof import('./src/components/binance/StatsCards.vue')['default']
    StatsSummary: typeof import('./src/components/bot/StatsSummary.vue')['default']
    TaskActionBar: typeof import('./src/components/tasks/TaskActionBar.vue')['default']
    TaskFormModal: typeof import('./src/components/tasks/TaskFormModal.vue')['default']
    TaskHistoryModal: typeof import('./src/components/tasks/TaskHistoryModal.vue')['default']
    TaskList: typeof import('./src/components/tasks/TaskList.vue')['default']
    TaskManageModal: typeof import('./src/components/tasks/TaskManageModal.vue')['default']
    TaskRemarkModal: typeof import('./src/components/tasks/TaskRemarkModal.vue')['default']
    TaskSectionHeader: typeof import('./src/components/tasks/TaskSectionHeader.vue')['default']
    Toast: typeof import('./src/components/common/Toast.vue')['default']
    TradeConfig: typeof import('./src/components/bot/TradeConfig.vue')['default']
    TradeLog: typeof import('./src/components/bot/TradeLog.vue')['default']
    UserInfo: typeof import('./src/components/bot/UserInfo.vue')['default']
    UserSelector: typeof import('./src/components/common/UserSelector.vue')['default']
  }
}
