/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddRecordModal: typeof import('./src/components/profit/AddRecordModal.vue')['default']
    BaseModal: typeof import('./src/components/common/BaseModal.vue')['default']
    Calendar: typeof import('./src/components/profit/Calendar.vue')['default']
    ConnectionStatus: typeof import('./src/components/bot/ConnectionStatus.vue')['default']
    FloatingButtons: typeof import('./src/components/bot/FloatingButtons.vue')['default']
    Header: typeof import('./src/components/profit/Header.vue')['default']
    LoadingSpinner: typeof import('./src/components/common/LoadingSpinner.vue')['default']
    LogModal: typeof import('./src/components/profit/LogModal.vue')['default']
    OrderHistory: typeof import('./src/components/bot/OrderHistory.vue')['default']
    PriceInfo: typeof import('./src/components/bot/PriceInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsModal: typeof import('./src/components/profit/SettingsModal.vue')['default']
    StatsCards: typeof import('./src/components/profit/StatsCards.vue')['default']
    StatsSummary: typeof import('./src/components/bot/StatsSummary.vue')['default']
    Toast: typeof import('./src/components/common/Toast.vue')['default']
    TradeConfig: typeof import('./src/components/bot/TradeConfig.vue')['default']
    TradeLog: typeof import('./src/components/bot/TradeLog.vue')['default']
    UserInfo: typeof import('./src/components/bot/UserInfo.vue')['default']
    UserSelector: typeof import('./src/components/profit/UserSelector.vue')['default']
  }
}
